[workspace]
authors = ["Matthew W. Thompson <mattwthompson@protonmail.com>"]
channels = ["conda-forge"]
name = "demo"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
nglview = "*"
jupyterlab = "*"

[pypi-dependencies]
# unclear how to add pypi-dependencies into a feature with unreleased packages
openadmet-toolkit = { git = "https://github.com/OpenADMET/openadmet-toolkit.git" }

[feature.lint]
dependencies = {ruff = "*"}

[feature.openff]
dependencies = {openff-toolkit-examples = "==0.16.8"}  # update to 0.17.0

[feature.openfe]
dependencies = {openfe = "==1.3.1"}  # update to 1.4.0

[environments]
demo = {features = ["lint", "openff", "openfe"]}

